#include <string>
#include <vector>
#include <stdexcept>

// 假设 NameValuePair 类已经实现
//#include "NameValuePair.cpp"

// 假设 HeaderElement 类已经实现，并且有 parse 和 parseElements 方法
#include "HeaderElement.cpp"


//##None
class Header : public NameValuePair {
private:
    bool isAutogenerated;

public:
    // ----------------------------------------------------------- Constructors

    /**
     * Default constructor.
     */
    Header() : NameValuePair("", ""), isAutogenerated(false) {} //#isAutogenerated 不是类 "Header" 的非静态数据成员

    /**
     * Constructor with name and value
     *
     * @param name the header name
     * @param value the header value
     */
    Header(const std::string& name, const std::string& value) 
        : NameValuePair(name, value), isAutogenerated(false) {}

    /**
     * Constructor with name and value
     *
     * @param name the header name
     * @param value the header value
     * @param isAutogenerated true if the header is autogenerated,
     *  false otherwise.
     * 
     * @since 3.0
     */
    Header(const std::string& name, const std::string& value, bool isAutogenerated) 
        : NameValuePair(name, value), isAutogenerated(isAutogenerated) {}

    // --------------------------------------------------------- Public Methods

    /**
     * Returns a {@link String} representation of the header.
     *
     * @return stringHEAD
     */
    std::string toExternalForm() const {  //#None
        return (getName().empty() ? "" : getName()) 
            + ": " 
            + (getValue().empty() ? "" : getValue()) 
            + "\r\n";
    }

    /**
     * Returns a {@link String} representation of the header.
     *
     * @return stringHEAD
     */
    std::string toString() const {  //#None
        return toExternalForm();
    }

    /**
     * Returns an array of {@link HeaderElement}s
     * constructed from my value.
     *
     * @see HeaderElement#parse
     * @throws std::runtime_error if the header cannot be parsed
     * @return an array of header elements
     * 
     * @deprecated Use #getElements
     */
    std::vector<HeaderElement> getValues() const {  //None
        try {
            return HeaderElement::parse(getValue());
        } catch (const std::exception& e) {
            throw std::runtime_error("Header cannot be parsed");
        }
    }

    /**
     * Returns an array of {@link HeaderElement}s
     * constructed from my value.
     *
     * @see HeaderElement#parseElements(String)
     * 
     * @return an array of header elements
     * 
     * @since 3.0
     */
    std::vector<HeaderElement> getElements() const {  //#None
        return HeaderElement::parseElements(getValue());
    }

    /**
     * Returns the value of the auto-generated header flag.
     * 
     * @return true if the header is autogenerated,
     *  false otherwise.
     * 
     * @since 3.0
     */
    bool isAutogenerated() const { //#isAutogenerated 不是类 "Header" 的非静态数据成员
        return isAutogenerated;
    }


};

/*
说明：
继承：Header 类继承自 NameValuePair 类。

构造函数：C++ 的构造函数与 Java 类似，但不需要 public 关键字。

方法：C++ 的方法与 Java 类似，但需要注意返回类型和参数类型的差异。

异常处理：在 C++ 中，异常处理使用 try-catch 块，并且需要手动抛出异常。

字符串处理：C++ 使用 std::string 来处理字符串，而不是 Java 的 String 类。

依赖项：
NameValuePair 类需要已经实现，并且有 getName 和 getValue 方法。

HeaderElement 类需要已经实现，并且有 parse 和 parseElements 方法。

注意事项：
C++ 中没有 @deprecated 和 @since 注释，这些注释在代码中被省略。

C++ 中没有 null，使用 nullptr 或者空字符串来表示空值。
*/