//�����ǽ�Java���뷭���C++�İ汾��������ص��������`NameValuePair`��`HeaderElement`���Ѿ�ʵ�֡�

//```cpp
#include <string>
#include <stdexcept>

class HeaderElement; // ����HeaderElement�Ѿ�ʵ��

class Header : public NameValuePair {
public:
    // ----------------------------------------------------------- Constructors

    /**
     * Autogenerated header flag.
     */
    bool isAutogenerated;
    
    /**
     * Default constructor.
     */
    Header() : NameValuePair(nullptr, nullptr), isAutogenerated(false) {}

    /**
     * Constructor with name and value
     *
     * @param name the header name
     * @param value the header value
     */
    Header(const std::string& name, const std::string& value)
        : NameValuePair(name, value), isAutogenerated(false) {}

    /**
     * Constructor with name and value
     *
     * @param name the header name
     * @param value the header value
     * @param isAutogenerated <tt>true</tt> if the header is autogenerated,
     *  <tt>false</tt> otherwise.
     * 
     * @since 3.0
     */
    Header(const std::string& name, const std::string& value, bool isAutogenerated)
        : NameValuePair(name, value), isAutogenerated(isAutogenerated) {}

    // --------------------------------------------------------- Public Methods

    /**
     * Returns a {@link String} representation of the header.
     *
     * @return stringHEAD
     */
    std::string toExternalForm() const {
        return (getName().empty() ? "" : getName()) 
            + ": " 
            + (getValue().empty() ? "" : getValue()) 
            + "\r\n";
    }

    /**
     * Returns a {@link String} representation of the header.
     *
     * @return stringHEAD
     */
    std::string toString() const {
        return toExternalForm();
    }

    /**
     * Returns an array of {@link HeaderElement}s
     * constructed from my value.
     *
     * @see HeaderElement#parse
     * @throws std::runtime_error if the header cannot be parsed
     * @return an array of header elements
     * 
     * @deprecated Use #getElements
     */
    std::vector<HeaderElement> getValues() const {
        try {
            return HeaderElement::parse(getValue());
        } catch (const std::exception& e) {
            throw std::runtime_error("Header cannot be parsed: " + std::string(e.what()));
        }
    }

    /**
     * Returns an array of {@link HeaderElement}s
     * constructed from my value.
     *
     * @see HeaderElement#parseElements(String)
     * 
     * @return an array of header elements
     * 
     * @since 3.0
     */
    std::vector<HeaderElement> getElements() const {
        return HeaderElement::parseElements(getValue());
    }

    /**
     * Returns the value of the auto-generated header flag.
     * 
     * @return <tt>true</tt> if the header is autogenerated,
     *  <tt>false</tt> otherwise.
     * 
     * @since 3.0
     */
    bool isAutogenerated() const {
        return isAutogenerated;
    }
};
// ```

// ### ˵����
// 1. **�̳�**��`Header`��̳���`NameValuePair`�������C++��ʹ��`public NameValuePair`����ʾ�̳й�ϵ��
// 2. **���캯��**��C++�Ĺ��캯����Java���ƣ�����Ҫע���ʼ���б���ʹ�á�
// 3. **����**��C++�еķ���Ĭ����`inline`�ģ���˿���ֱ�����ඨ����ʵ�֡�
// 4. **�쳣����**��Java�е�`HttpException`��C++�б��滻Ϊ`std::runtime_error`������һ�ֳ������쳣���͡�
// 5. **�ַ�������**��C++�е��ַ���ʹ��`std::string`����Java�е�`String`���ơ�

// ��ȷ��`NameValuePair`��`HeaderElement`���Ѿ���ȷʵ�֣�������Java�汾����Ϊһ�¡�