以下是将Java代码翻译成C++的版本。假设相关的依赖项（如`NameValuePair`和`HeaderElement`）已经实现。

```cpp
#include <string>
#include <vector>
#include <stdexcept>

class HeaderElement; // 假设HeaderElement已经实现

class Header : public NameValuePair {
public:
    // ----------------------------------------------------------- Constructors

    /**
     * Autogenerated header flag.
     */
    bool isAutogenerated;
    
    /**
     * Default constructor.
     */
    Header() : NameValuePair(nullptr, nullptr), isAutogenerated(false) {}

    /**
     * Constructor with name and value
     *
     * @param name the header name
     * @param value the header value
     */
    Header(const std::string& name, const std::string& value)
        : NameValuePair(name, value), isAutogenerated(false) {}

    /**
     * Constructor with name and value
     *
     * @param name the header name
     * @param value the header value
     * @param isAutogenerated <tt>true</tt> if the header is autogenerated,
     *  <tt>false</tt> otherwise.
     * 
     * @since 3.0
     */
    Header(const std::string& name, const std::string& value, bool isAutogenerated)
        : NameValuePair(name, value), isAutogenerated(isAutogenerated) {}

    // --------------------------------------------------------- Public Methods

    /**
     * Returns a {@link String} representation of the header.
     *
     * @return stringHEAD
     */
    std::string toExternalForm() const {
        return (getName().empty() ? "" : getName()) 
            + ": " 
            + (getValue().empty() ? "" : getValue()) 
            + "\r\n";
    }

    /**
     * Returns a {@link String} representation of the header.
     *
     * @return stringHEAD
     */
    std::string toString() const {
        return toExternalForm();
    }

    /**
     * Returns an array of {@link HeaderElement}s
     * constructed from my value.
     *
     * @see HeaderElement#parse
     * @throws std::runtime_error if the header cannot be parsed
     * @return an array of header elements
     * 
     * @deprecated Use #getElements
     */
    std::vector<HeaderElement> getValues() const {
        try {
            return HeaderElement::parse(getValue());
        } catch (const std::exception& e) {
            throw std::runtime_error("Header cannot be parsed: " + std::string(e.what()));
        }
    }

    /**
     * Returns an array of {@link HeaderElement}s
     * constructed from my value.
     *
     * @see HeaderElement#parseElements(String)
     * 
     * @return an array of header elements
     * 
     * @since 3.0
     */
    std::vector<HeaderElement> getElements() const {
        return HeaderElement::parseElements(getValue());
    }

    /**
     * Returns the value of the auto-generated header flag.
     * 
     * @return <tt>true</tt> if the header is autogenerated,
     *  <tt>false</tt> otherwise.
     * 
     * @since 3.0
     */
    bool isAutogenerated() const {
        return isAutogenerated;
    }
};
```

### 说明：
1. **继承**：`Header`类继承自`NameValuePair`，假设`NameValuePair`类已经实现。
2. **构造函数**：C++中的构造函数与Java中的构造函数类似，但需要注意初始化列表的使用。
3. **方法**：`toExternalForm`和`toString`方法返回头部的字符串表示。`getValues`和`getElements`方法返回解析后的`HeaderElement`数组。
4. **异常处理**：在Java中，`HttpException`被抛出，而在C++中，我们使用`std::runtime_error`来表示解析错误。
5. **布尔类型**：Java中的`boolean`类型在C++中对应`bool`。

请确保`NameValuePair`和`HeaderElement`类已经正确实现，并且与Java版本的行为一致。