# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l0RVPepu375WFvuA5FkwBzrnZhm36C5Y
"""

import os
from huggingface_hub import HfFolder

os.environ["HF_TOKEN"] = HfFolder.get_token()
os.environ["HUGGINGFACE_HUB_TOKEN"] = os.environ["HF_TOKEN"]
print("exported:", bool(os.environ["HF_TOKEN"]))

from huggingface_hub import notebook_login
notebook_login()

from huggingface_hub import HfFolder, whoami
t = HfFolder.get_token()
print("token_loaded:", bool(t))
print(whoami(token=t)["name"])

!python simpy_pipeline.py \
  --zip /content/SimPy-master.zip \
  --install-deps \
  --all

from google.colab import drive
drive.mount('/content/drive')

import os, time

ts = time.strftime("%Y%m%d-%H%M%S")
SAVE_DIR = f"/content/drive/MyDrive/SimPy_experiments/{ts}"
os.makedirs(SAVE_DIR, exist_ok=True)

print("SAVE_DIR =", SAVE_DIR)

import shutil
from pathlib import Path

# 源文件
SRC_TOKEN_CSV = "/content/SimPy-master/results/token_count.csv"
SRC_PIPELINE  = "/content/simpy_pipeline.py"
SRC_PROJECT   = "/content/SimPy-master"

# 目标
dst_token_csv = str(Path(SAVE_DIR) / "token_count.csv")
dst_pipeline  = str(Path(SAVE_DIR) / "simpy_pipeline.py")

# 复制
assert Path(SRC_TOKEN_CSV).exists(), f"not found: {SRC_TOKEN_CSV}"
assert Path(SRC_PIPELINE).exists(),  f"not found: {SRC_PIPELINE}"

shutil.copy2(SRC_TOKEN_CSV, dst_token_csv)
shutil.copy2(SRC_PIPELINE, dst_pipeline)

print("Saved:")
print(" -", dst_token_csv)
print(" -", dst_pipeline)

import os

print("Files in SAVE_DIR:")
for root, dirs, files in os.walk(SAVE_DIR):
    level = root.replace(SAVE_DIR, "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = "  " * (level + 1)
    for f in files:
        print(f"{subindent}{f}")